### ISSUE TITLE
Problem Starting program

### ISSUE THREAD

**Issue by Superman627** [forgoty/reimaging#1]
Everytime i try to open it up it doesn't work it just shuts off quickly after i open it

**Comment by forgoty** [comment]
> Everytime i try to open it up it doesn't work it just shuts off quickly after i open it

Hello. Ive updated the source. Check it out.
Try to reinstall pyvk module with command:
`pip install git+https://github.com/mkuznets/pyvk.git`
PyPi has wrong module version.

And, can you show your console output?
